### ISSUE TITLE
Deprecation warnings triggered by addons could have more debug info

### ISSUE THREAD

**Issue by BryanCrotaz** [ember-cli/ember-cli-htmlbars#105]
Is it possible for a deprecation warning to list the stack of addons that it was caused by?

It's all too easy for a deprecation to be caused by an addon loaded by an an addon, loaded by... you get the point. It's very labour intensive to find the addon that's loaded an old version of htmlbars (for example).

**Comment by rwjblue** [comment]
In general, it should be possible to list the hierarchy with `npm ls ember-cli-htmlbars` which should show you how a deprecated version is getting included without too much trouble. 

That being said, it does seem like a nice feature that we could add to ember-cli (but may require an RFC). I'm thinking specifically about making each addons `this.ui` be tailored to its inclusion "path" (meaning it's parent addons).

**Comment by rwjblue** [comment]
To summarize what I mean above: we should make `this.ui` aware of stack similar to `heimdalljs-logger`, but needs someone to champion to push forward.

Closing this issue though, as it is unlikely that we will do anything here but follow the normal pattern (logging via `this.ui.writeLine`).
