### ISSUE TITLE
Pass AST Plugins to each `compile`

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli-htmlbars#119]
This would need to detect Ember version, and when possible avoid calling `registerPlugin` (which mutates closure scope and requires bizarre cache clearing shenanigans). Instead of `registerPlugin` we would pass the plugins directly to the `compile` invocation (in `options.plugins.ast`).

Related to #116.

**Comment by rwjblue** [comment]
Implemented in #130, but needs a bit of a rebase in order to be able to land.

**Comment by fivetanley** [comment]
@rwjblue Does this mean that I would be able to write an ember addon that registers an ember-cli-htmlbars plugin and it would affect the compilation output of all the addons included in an app (vs just the app's templates)? If so I'd be happy to take a stab at rebasing #130.

**Comment by rwjblue** [comment]
@fivetanley - No it isn't quite exposing that capability, though it could be leveraged to do so (I think). This is specifically talking about _pre_registration of AST plugins taht we do, which ultimately mutates global state inside the evaluated `ember-template-compiler.js`. Because of that mutation, we are forced to bust the cache and re-require `ember-template-compiler.js` many times (resulting in non-trivial build cost, memory bloat, etc).

**Comment by rwjblue** [comment]
Implemented in #661
