### ISSUE TITLE
No CHANGELOG.md or documentation of changes in the release notes.  

### ISSUE THREAD

**Issue by mileslane** [ember-cli/ember-cli-htmlbars#128]
I want to know what breaking changes there are in the 3.0.x series compared to the 2.0.x series.  I am unable to find any documentation for this.

**Comment by ncoden** [comment]
Poke @rwjblue

**Comment by apellerano-pw** [comment]
I was wondering this today too. At the very least based off https://github.com/ember-cli/ember-cli-htmlbars/compare/v2.0.5..v3.0.1 there would be what constitutes a semver breaking change by dropping Node 4 support.

**Comment by rwjblue** [comment]
Ya, the breaking change in v3 was dropping support for Node 4.

**Comment by rwjblue** [comment]
I've been trying to be better about this, new releases should have release notes in the GH releases page.

Going to close this for now...
