### ISSUE TITLE
"unreachable" error in 3.0.0 with "img" argument

### ISSUE THREAD

**Issue by epchristi** [ember-cli/ember-cli-htmlbars#138]
When using |img| in template, I get "unreachable" errors. If I use image, it works.

{{#each model.Gallery.images as |img|}}
					<div class="gallery-image"><img src="assets/gallery/{{model.Gallery.path}}/{{img.src}}"></div>
{{/each}}

**Comment by rwjblue** [comment]
Sorry about the troubles, this sounds very much like the issue reported in https://github.com/emberjs/ember.js/issues/16826. As you identified the work around is to avoid using a block param name that is also an html element.

Closing this issue (we are tracking the solution over in https://github.com/emberjs/ember.js/issues/16826)...
