### ISSUE TITLE
template-specific cache invalidation for ast plugins

### ISSUE THREAD

**Issue by chriseppstein** [ember-cli/ember-cli-htmlbars#227]
AST Plugins may make different changes to a template based on other state of the project. (For instance, a plugin might rewrite css classes based on content within css files.)

Right now, [the `cacheKey` option is invoked during plugin registration][cache_key_invocation]. This lets the ast addon invalidate based on configuration, but not based on the application state specific to the template.

The template path can be connected to the cache key here: https://github.com/ember-cli/ember-cli-htmlbars/blob/312cf133b68f482e896bf58729965f13c5ca0b75/index.js#L118

I'd like to submit a fix for this. My plan is to delay invocation of `cacheKey()` until `cacheKeyProcessString` is invoked. The cacheKey function provided by the addon that provides the ast plugin, would be passed the path to the template file. 

[cache_key_invocation]: https://github.com/ember-cli/ember-cli-htmlbars/blob/312cf133b68f482e896bf58729965f13c5ca0b75/ember-addon-main.js#L139

**Comment by rwjblue** [comment]
@chriseppstein - I _think_ this was addressed by #238, can you confirm (and close if it was)?

**Comment by chriseppstein** [comment]
The bits of this PR that were salvageable were merged in with 238. Closing.
