### ISSUE TITLE
Implement stable caching (and tests) for colocation compilation.

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli-htmlbars#290]
The main implementation in #249 did the semi-naive thing of building the output tree **every time** without caching. Before we can enable this by default for all scenarios, we _must_ implement a caching system that ensures the output tree is stable if none of the things changed here are modified.

**Comment by rwjblue** [comment]
Done in https://github.com/ember-cli/ember-cli-htmlbars/pull/384

**Comment by btecu** [comment]
@rwjblue Was this actually implemented in #380?

**Comment by rwjblue** [comment]
Do'h 🤦‍♂, yes thank you @btecu
