### ISSUE TITLE
AST plugins not applied to tagged template strings

### ISSUE THREAD

**Issue by dfreeman** [ember-cli/ember-cli-htmlbars#307]
Opening this here so there's a place to track the issue. This originally came up [in Discord](https://discordapp.com/channels/480462759797063690/514504648590098457/626111902187257856) in the context of colocated templates (since they're implemented via tagged template strings), but it also applies to templates embedded in JS files directly by users.

AST plugins don't seem to be getting applied to embedded templates. I set up a [simple reproduction](https://github.com/dfreeman/colocated-components-no-template-transforms/commit/0c889317e6eb7f854276541394b708aaabd47464) where the plugin just emits a message to the console when it processes a template. The message is logged for templates that are preprocessed the usual way, but not for those using the `hbs` tag from `ember-cli-htmlbars`.

Poking around a little, this seems to be related to the template compiler using global state for configured plugins and the way we have to [muck with this state](https://github.com/ember-cli/ember-cli-htmlbars/blob/master/lib/utils.js#L44) to support different plugins in different contexts, but I wasn't able to come up with a fix in the time I spent playing with it.

**Comment by rwjblue** [comment]
Still a few TODO items left, but https://github.com/ember-cli/ember-cli-htmlbars/pull/309 aims to fix this. I confirmed locally, with those changes the plugin in the reproduction is called for the inlined template.

**Comment by rwjblue** [comment]
Fix is landed and released as https://github.com/ember-cli/ember-cli-htmlbars/releases/tag/v4.0.2.

**Comment by rwjblue** [comment]
FYI - I just confirmed in the demo repo with 4.0.2 that the plugin added there does get called. Sent a PR here (only change is bumping ember-cli-htmlbars though): https://github.com/dfreeman/colocated-components-no-template-transforms/pull/1.
