### ISSUE TITLE
BUG: Templates are not re-exported as modules

### ISSUE THREAD

**Issue by gossi** [ember-cli/ember-cli-htmlbars#329]
With version 4 and my setup, templates are not re-exported as modules (same code works with version 3).

Repro is available here: https://github.com/gossi/repro-ember-cli-htmlbars-template-modules

**Comment by rwjblue** [comment]
Hmm, it’s not immediately obvious to me where this issue is coming from. I’m on mobile atm, could you tell me the result of `console.log(Object.keys(requires.entries))`?

**Comment by rwjblue** [comment]
Would you also mind testing what happens if you remove the `setEdition` call in your `.ember-cli.js` file? (This will help isolate if the issue is with the colocation code or something else...)

**Comment by gossi** [comment]
I checked `requirejs.entries` which is missing the template modules.

Just tested, it works without the `setEdition()`.
