### ISSUE TITLE
Re-exporting co-location components from nested folder

### ISSUE THREAD

**Issue by mydea** [ember-cli/ember-cli-htmlbars#330]
Co-location in nested folders is generally working fine for me, except for one case:

I just tried moving an (internal) addon to use co-location, and it does not work if I have a folder structure like this (omitting all .js files for the components, for simplicity)

- addon
  - components
    - my-component
       - sub-a.hbs
       - sub-b.hbs
    - my-component.hbs
- app
  - components
    - my-component
       - sub-a.js
       - sub-b.js
    - my-component.js

Where the `app/components/my-component.js` re-export looks like this:

```js
export {
  default
} from 'my-addon/components/my-component';
```

It will not find this component in the app.
It works if I move that file to `app/components/my-component/index.js` instead.

(Superseding my comment in https://github.com/emberjs/ember.js/issues/18255)

This is with ember-source@3.13.x & ember-cli-htmlbars@4.0.5.

**Comment by rwjblue** [comment]
Thank you for opening this!

**Comment by rwjblue** [comment]
@mydea - I can't reproduce this 🤔.

I created a branch [over here](https://github.com/rwjblue/repro-ember-cli-htmlbars-template-modules/compare/master...repro-330) with the same setup that you described above, and all three components can be rendered. Can you take a look at that repro and see if I've done something wrong, or possible send me a PR that replicates the issue you hit?

**Comment by rwjblue** [comment]
Is it possible that you were hitting issues from #333? I don't recall if you mentioned you were using TypeScript or no...

**Comment by rwjblue** [comment]
@mydea - Any help identifying whats going on would be useful.

**Comment by mydea** [comment]
OK, I went back to try it again and it works just fine now for me as well - not sure what exactly was wrong there. Maybe I didn't update something properly, or I just had a typo... Sorry for the confusion!
