### ISSUE TITLE
Compiler added to app registry but not to addons

### ISSUE THREAD

**Issue by teddyzeenny** [ember-cli/ember-cli-htmlbars#34]
`app.registry.add` only adds it to the app registry, which means we can't use HTMLbars if at least one of our addons has templates.

Adding `registry.add('template', 'ember-cli-htmlbars', ['hbs', 'handlebars']);` to ember-cli's `setupRegistry` only fixes this for Handlebars since this will cause it to go directly to `ember-cli-htmlbars/index.js` which is the precompiler that assumes HTMLbars is disabled.

**Comment by rwjblue** [comment]
Working on this in https://github.com/ember-cli/ember-cli/pull/3166 and https://github.com/ember-cli/ember-cli-htmlbars/pull/38.

**Comment by teddyzeenny** [comment]
This has been fixed in ember-cli 0.2! Thanks everyone who worked on this!
