### ISSUE TITLE
`<style>` tags with CSS comments cause invalid compilation

### ISSUE THREAD

**Issue by patocallaghan** [ember-cli/ember-cli-htmlbars#391]
ember-cli: 3.14.0
node: 10.15.0
os: darwin x64
ember-cli-htmlbars: 4.2.0

If I have co-located templates enabled with the below html, the presence of the CSS comment causes the assets compilation to break.

```hbs
<style>
  /* A comment */
  .some-class {
    background-color: rebeccapurple;
  }
</style>
```

The app fails to load with the following error in the console `Uncaught SyntaxError: Unexpected token '.'`

The output JS looks like the following:
![image](https://user-images.githubusercontent.com/685034/70665837-544f9e00-1c65-11ea-9cf2-c4fa0033e866.png)

Removing the CSS comment makes the template compilation work as expected

Reproduction repo: https://github.com/patocallaghan/htmlbars-bug (Relevant changes in [this commit](https://github.com/patocallaghan/htmlbars-bug/commit/3e4be44c2df42551d907173c12923a6701d165c0)) 

Edit: I can migrate these to be handlebars comments but worth raising as it would be a breaking change

**Comment by rwjblue** [comment]
Thank you for reporting!

**Comment by rwjblue** [comment]
The fix is released in babel-plugin-htmlbars-inline-precompile@3.0.1, if you update your lockfile to use that it should fix things (without a change to ember-cli-htmlbars).

I am bumping in ember-cli-htmlbars though "just in case", to help make sure other users don't run into the issue (over in #392).

**Comment by patocallaghan** [comment]
Thanks for the quick turnaround 🙇
