### ISSUE TITLE
0.7.0 breaks ember 1.9.1 apps?

### ISSUE THREAD

**Issue by ef4** [ember-cli/ember-cli-htmlbars#40]
I think I'm seeing that 0.7.0 won't work with an Ember 1.9.1 app anymore. Somebody following the upgrade instructions from 1.8 to 1.9 is going to end up with 0.7.0 and a broken install.

Possibly this should have received a major version bump?

**Comment by rwjblue** [comment]
Documented in the README [here](https://github.com/ember-cli/ember-cli-htmlbars#handlebars-20-support), and we did bump "major" (for a non 1.0.0 project) from 0.6.0 to 0.7.0.

**Comment by ef4** [comment]
Ah right, that is major. My problem wasn't semver, it's that up until now I haven't had any semver constraint at all, because "newest" always worked.

This is for liquid-fire's CI, where it installs these deps dynamically based on the test matrix.

I can lock the version to 0.6.0 for ember 1.9.1.

**Comment by rwjblue** [comment]
@ef4 - Sorry for the troubles.  I needed to simplify the responsibilities here for some of the changes required by https://github.com/ember-cli/ember-cli/pull/3166 (and https://github.com/ember-cli/ember-cli-htmlbars/pull/38).
