### ISSUE TITLE
Could you please provide steps to get it installed

### ISSUE THREAD

**Issue by mxrguspxrt** [ember-cli/ember-cli-htmlbars#43]
Pretty please

**Comment by rwjblue** [comment]
What is "it"?

**Comment by rwjblue** [comment]
You install ember-cli-htmlbars like most other NPM packages: `npm install --save-dev ember-cli-htmlbars`.

**Comment by mxrguspxrt** [comment]
Thank you for the response. Would it nice to be reminded in the readme?
