### ISSUE TITLE
Tries and fails to parse HBS files in non template directory

### ISSUE THREAD

**Issue by mehulkar** [ember-cli/ember-cli-htmlbars#466]
Repro:

1. ember new foo && cd foo
1. mkdir -p app/.somedir/a/b
1. echo "{{> mypartial }}" > app/.somedir/a/b/c.hbs
1. ember build

```
$ ember build
Environment: development
⠧ building... [BroccoliRollup > rollup]Non-existent export 'default' is imported from -private/ts-interfaces/record-data.js
Non-existent export 'default' is imported from -private/ts-interfaces/record-data.js
⠹ building... [Babel: ember-data > applyPatches]'@ember-data/model/-private' is imported by -private/index.js, but could not be resolved – treating it as an external dependency
cleaning up...
Template Compiler Error (broccoli-persistent-filter:TemplateCompiler) in foo/.somedir/a/b/c.hbs

Handlebars partials are not supported: "{{> mypartial" at L1:C0


Stack Trace and Error Report: /var/folders/bf/vg2wsvj91vq9kjmyjflpy_880000gn/T/error.dump.8aecd600644c85bedfc583928a21c69a.log
```

**Comment by mehulkar** [comment]
This is happening to us because our CI system is adding this directory into our `app/`. Although the CI system should probably not do this, it also seems weird that Ember would try to look in this directory at all for .hbs files. 

I believe this could be avoided by either changing the `inputTree` to the TemplateCompiler here: https://github.com/ember-cli/ember-cli-htmlbars/blob/v4.2.3/lib/ember-addon-main.js#L87 or for the TemplateCompiler to only look in a safe list of directories, but I'm not sure how this gets configured.

**Comment by mehulkar** [comment]
https://github.com/ember-cli/ember-cli/issues/8049 looks related

**Comment by mehulkar** [comment]
Reading over broccoli-persistent-filter, it seems that implementing `getDestFilePath` in the TemplateCompiler to pass over a certain subset of files, is the answer?

**Comment by mehulkar** [comment]
I was able to make this work locally by adding copying over the implementation from `BroccoliPersistentFilter` and adding in an additional check to make sure the relativePath matched   `templates` or `components`. Some smarter check would probably be better:

https://github.com/broccolijs/broccoli-persistent-filter/blob/v2.3.1/index.js#L388-L409

**Comment by rwjblue** [comment]
> it also seems weird that Ember would try to look in this directory at all for .hbs files.

This assumption is incorrect. The changes made in ember-cli@3.13+ (and here in ember-cli-htmlbars@4+) are specifically intended to allow putting `.hbs` files throughout the folder structure. This is not an accident or bug, and is very unlikely to be changed at this point. Putting invalid `.hbs` files (from Ember's perspective) in the `app/` structure, just isn't something that we support.

There are some things you could do to mitigate (by filtering the trees before passing them into the build):

```js
// ember-cli-build.js

module.exports = function(defaults) {
  let app = new EmberApp(defaults, {
    trees: {
      app: new Funnel('app', {
        exclude: ['.somedir/**/*'],
      }),
    }
  });

  return app.toTree();
};
```

Note: this is not guaranteed to continue to work with alternate build systems (e.g. Embroider).

**Comment by mehulkar** [comment]
Very interesting to know! What is this in preparation for? I would have assumed that being able to know where things are is the benefit of a defined folder structure?

**Comment by rwjblue** [comment]
Component template colocation required that templates live other places than app/templates (they would now be in app/components). I would expect that we eventually do something similar for route templates (still to be designed), and we are currently working on unblocking template imports (which would allow importing other components from anywhere).

**Comment by mehulkar** [comment]
Hmm ok. Definitely sounds like I should close this. One last q... would it make sense to log a warning instead of throwing an error in this case? Here's where it catches and then rethrows build errors:

https://github.com/ember-cli/ember-cli-htmlbars/blob/v4.2.3/lib/template-compiler-plugin.js#L91

**Comment by rwjblue** [comment]
Not sure? I think throwing is correct in this case (as far as we can tell the app is completely broken, and we cannot finish the build).
