### ISSUE TITLE
No type declaration provided

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-cli/ember-cli-htmlbars#468]
Update: https://github.com/ember-cli/ember-cli-htmlbars/issues/468#issuecomment-598123778

-------------------------------------------

I'm getting this error with `tsc` on my project:

```
 $ yarn tsc

types/ember-cli-htmlbars.d.ts:1:70 - error TS2304: Cannot find name 'TemplateFactory'.

1 export function hbs(template: TemplateStringsArray, ...args: any[]): TemplateFactory;
                                                                       ~~~~~~~~~~~~~~~
```

**Comment by NullVoxPopuli** [comment]
oh nevermind, this is actually a different issue.

turns out that type error is from my own types. 
When I remove my custom ember-cli-htmlbars types, I get:
```
 error TS7016: Could not find a declaration file for module 'ember-cli-htmlbars'. '{project}/node_modules/ember-cli-htmlbars/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/ember-cli-htmlbars` if it exists or add a new declaration (.d.ts) file containing `declare module 'ember-cli-htmlbars';`

4 import { hbs } from 'ember-cli-htmlbars';
```

**Comment by rwjblue** [comment]
Hmm, where do these types come from?

**Comment by NullVoxPopuli** [comment]
doh, that was a custom type declaration file I had forgotten about.

```
tests/integration/components/pod/chat/chat-entry/embeds-menu/component-test.ts:4:21 - error TS7016: Could not find a declaration file for module 'ember-cli-htmlbars'. 'C:/Users/Preston/Documents/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/ember-cli-htmlbars/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/ember-cli-htmlbars` if it exists or add a new declaration (.d.ts) file containing `declare module 'ember-cli-htmlbars';`

4 import { hbs } from 'ember-cli-htmlbars';
```
the real error is that there are no types :(

**Comment by rwjblue** [comment]
> the real error is that there are no types :(

I think we may disagree about that being an error 😉

**Comment by rwjblue** [comment]
We are not going to ship types here without addressing the larger issue of how to  avoid being stuck forever on a single TypeScript version (because bumping TypeScript even a minor version is very commonly a breaking change).

I'd suggest filing an issue (or PR) to fix this over in definitely typed.
