### ISSUE TITLE
Merging compiled templates into app.js

### ISSUE THREAD

**Issue by rwwagner90** [ember-cli/ember-cli-htmlbars#47]
I have some common components and templates that I need to include in multiple Ember-CLI apps. Unless there is a way to specify that my common/templates folder also be watched, just like app/templates, I figured I would need to use this to do it in my Brocfile myself. I've currently got this:
```js
var commonTemplates = new HtmlbarsCompiler('../common/templates/components', {
  isHTMLBars: true,

  // provide the templateCompiler that is paired with your Ember version
  templateCompiler: require('./bower_components/ember/ember-template-compiler')
});

// Merge the app tree and all of our common assets
module.exports = mergeTrees([app.toTree(), commonImages, commonFonts, commonTemplates]);
```

This is copying each template into it's own js file in dist/ though. How can I make them be added to app.js, like the ones from the app folder?

Also, I know it's not related to this library, but I'll need a way of grabbing all the components and other ember files and doing similar things, if you could point me in the right direction please.

**Comment by rondale-sc** [comment]
@rwwagner90 You can do in-app addons to include local addons that you don't want to publish to NPM.  

`ember g in-repo-addon foo`

That will create two files and modify your package.json.  More information can be found [here](http://www.ember-cli.com/#detailed-list-of-blueprints-and-their-use)

Check out the [ADDON_HOOKS](https://github.com/ember-cli/ember-cli/blob/master/ADDON_HOOKS.md) to see how you can modify the build with the proper hooks and stuff.

(side note: I think it is a bit of a no-no to use the HTMLBarsCompiler directly, you might end up running into issues)

**Comment by rwwagner90** [comment]
@rondale-sc I cannot do an in app addon. It needs to be in multiple apps, so I would have to maintain the code in multiple apps, right? I don't see how an in app addon is any different than just putting the code in the app in the first place? Is there any documentation on in app addons?

**Comment by rwwagner90** [comment]
Closing, as this is old, and *hopefully* no longer a problem for people
