### ISSUE TITLE
Hammer actions aren't recognized

### ISSUE THREAD

**Issue by Blackening999** [ember-cli/ember-cli-htmlbars#48]
Hello,

I have noticed ignorance of Hammer events - aren't recognised/initiated pan/tap/swipe actions. I haven't dived deeper due to the lack of time. The issue has been resolved with setting fixed **0.7.4** version. I'm using Hammer  2.0.4, ember 1.10 and ember-cli 0.1.5. Detected in Chrome browser.

Regards

**Comment by Turbo87** [comment]
seems to work fine for https://github.com/runspired/ember-gestures

closing this as most likely outdated
