### ISSUE TITLE
Why does this still use bower?

### ISSUE THREAD

**Issue by BryanCrotaz** [ember-cli/ember-cli-htmlbars#487]
`ember-template-compiler` is being requested from `bower_components`. Now that there's an npm package, should we not be using it?

I've upgraded my addon to ember 3.17 with ember upgrade, and I've run codemods. Now I'm getting a build error, `Cannot find module ... bower_components/ember/ember-template-compiler.js`

From reading the source code, it seems like `ember-source` is expected to be present. Should this be in the dependencies?

**Comment by BryanCrotaz** [comment]
`ember install ember-cli-htmlbars` neither installs ember-source, nor the required bower package.

**Comment by BryanCrotaz** [comment]
`ember install ember-source` is a working workaround, but the error message doesn't point the dev at this solution

**Comment by rwjblue** [comment]
I'm not sure I understand the question. We definitely do not use `bower_components` by default, though we do still have supporting code to discover the template compiler from there if we can't find it as a normal npm package.

**Comment by rwjblue** [comment]
Specifically, this code:

https://github.com/ember-cli/ember-cli-htmlbars/blob/ff934eb3972d4089bfc60b799f7861b1a0cbc504/lib/ember-addon-main.js#L194-L199

It checks the project for `ember-source`, then falls back to the older `bower_componetns/ember/ember-template-compiler.js` location.

**Comment by rwjblue** [comment]
@BryanCrotaz - In your scenario, is the `ember-source` **not** found by `this.project.findAddonByName('ember-source')`?

**Comment by BryanCrotaz** [comment]
Yes, the above code is what led me to the solution, which narrows this down to being a misleading error message:

> `ember install ember-source` is a working workaround, but the error message doesn't point the dev at this solution

**Comment by BryanCrotaz** [comment]
We shouldn't need to scour source code to find out how to fix an issue :)

**Comment by rwjblue** [comment]
1) I disagree that reading code is bad, it is quite wonderful and empowering :smile:
2) I totally agree that we should fail loudly with a message about `ember-source` (not about `bower_components`) if we don't find the addon and `bower_components/ember/ember-template-compiler.js` is not present.

**Comment by BryanCrotaz** [comment]
It's wonderful and empowering, but it's not fast when you just want to get your upgrade done. It's fantastic when wanting to learn about Ember, but frameworks are valuable because you don't need to know everything about how they work. They just work.

**Comment by BryanCrotaz** [comment]
Also would be interesting to cross post this in ember-cli-update which should have installed ember-source during one of the updates?

**Comment by rwjblue** [comment]
Closed by https://github.com/ember-cli/ember-cli-htmlbars/pull/492
