### ISSUE TITLE
Add License File?

### ISSUE THREAD

**Issue by JohnQuaresma** [ember-cli/ember-cli-htmlbars#51]
Just wondering whether this package is covered under MIT license.  If so, would you mind adding a license file?

Thanks!

**Comment by rwjblue** [comment]
Yes, it is MIT as documented in the [package.json](https://github.com/ember-cli/ember-cli-htmlbars/blob/master/package.json#L22).

**Comment by Turbo87** [comment]
[LICENSE.md](https://github.com/ember-cli/ember-cli-htmlbars/blob/master/LICENSE.md) file has been added lately
