### ISSUE TITLE
Issues following Readme instructions for precompiling in an addon

### ISSUE THREAD

**Issue by sir-dunxalot** [ember-cli/ember-cli-htmlbars#55]
I'm trying to precompile HTMLBars template strings as described in the readme. However, I've come across two problems.

1. `find` is undefined - this is fairly easy to solve with native JS
2. the htmlbarsPlugin variable is equal to `{ name: 'ember-cli-htmlbars', ext: 'hbs', toTree: [Function] }` and does not have a `precompile` function.

The code I am referring to is:

```js
module.exports = {
  name: 'my-addon-name',

  setupPreprocessorRegistry: function(type, registry) {
    // Error 1 - find is not a function
    var htmlbarsPlugin = registry.load('template').find(function(plugin) {
      return plugin.name === 'ember-cli-htmlbars';
    });

    // Error 2 - precompile is not a function
    var precompiled = htmlbarsPlugin.precompile("{{my-component}}");
  }
};
```

Ember CLI version is 0.2.5. Ember version is 1.12.0.

**Comment by rwjblue** [comment]
You need the latest version to have a `precompile`.

**Comment by rwjblue** [comment]
The README is addressing ember-cli-htmlbars@0.7.7, can you please confirm you are using that version?

**Comment by sir-dunxalot** [comment]
Thanks for the quick response! I'm using `0.7.6`. I'll update and report back - it might be worth adding a quick note about the version to the readme because I'm using the version bundled with Ember CLI 0.2.5.

**Comment by rwjblue** [comment]
I'd happily merge a PR adding some verbiage to that effect, but I find in general that every projects README reflects its current version...

**Comment by sir-dunxalot** [comment]
Updating fixed the issue - thanks again. And whatever you prefer regarding the Readme - maybe this issue will be enough for people to avoid getting stung.
