### ISSUE TITLE
The minor update from `0.7.9` to `0.7.10` broke my ember app

### ISSUE THREAD

**Issue by renatocarvalho** [ember-cli/ember-cli-htmlbars#61]
Hey guys, I have just discovered that the `0.7.10` update was causing a problem to my ember app. Since it's a minor update, I think it wasn't supposed to break.

Here's the problem:

- The app loads fine for the first time
- When I make some change and the page reloads itself with the live-reload extension, nothing is loaded inside my ember-view.

<img width="402" alt="screen shot 2015-08-20 at 17 30 46" src="https://cloud.githubusercontent.com/assets/16294/9394877/44f33314-4761-11e5-9a37-ee22ffa3bcb5.png">

I don't know what information would be usefull for you guys to debug. Let me know what information you need.

**Comment by rwjblue** [comment]
What version of ember-cli are you using?

**Comment by rwjblue** [comment]
Can you share a repro of the problem?

**Comment by kategengler** [comment]
I filed a related sounding issue (but around tests) with ember-cli https://github.com/ember-cli/ember-cli/issues/4723 However, that is using 0.7.9

**Comment by stefanpenner** [comment]
broccoli-filter@1.2.1 released which should address this issue

```
rm -rf node_modules
npm cache clear
npm install
```

**Comment by renatocarvalho** [comment]
Sorry it took a long time to reply you guys. I was travelling.

Here's my `ember version`:
```
version: 1.13.8
node: 0.12.7
npm: 2.13.4
os: darwin x64
```

Here's my `ember-cli` version:
`"ember-cli": "1.13.8"`

Glad you guys have solved the issue, thanks! I'll test again!

**Comment by renatocarvalho** [comment]
I updated to `"ember-cli-htmlbars": "1.0.0"` and it's working fine to me now :smile:
