### ISSUE TITLE
Order of plugins seems to have changed in 5.6.0

### ISSUE THREAD

**Issue by simonihmig** [ember-cli/ember-cli-htmlbars#664]
Filed this other issue, but the root issue seems to be caused by the latest changes here: https://github.com/embroider-build/embroider/issues/701

**Comment by rwjblue** [comment]
Ugh. This is definitely a breaking change in #661 (accidental of course). By changing from `registerPlugin` to passing the arguments to `compile` I accidentally reversed the ordering.

**Comment by rwjblue** [comment]
The reason for this is that Ember internally **unshifts** plugins when calling `registerPlugins`.  I wrote that code, and have no clue why the hell I did it that way. 🤦 🤕 

https://github.com/emberjs/ember.js/blob/8c85b2b52f304d7ca3987f97d9d2fbf18bd40d37/packages/ember-template-compiler/lib/system/compile-options.ts#L154

```js
// pseudo code
const USER_PLUGINS = [];
function registerPlugin(plugin) {
    USER_PLUGINS = [plugin, ...USER_PLUGINS];
}
```

**Comment by rwjblue** [comment]
OK, I've tried to address this in https://github.com/ember-cli/ember-cli-htmlbars/releases/tag/v5.6.2. Can you confirm @simonihmig?

**Comment by simonihmig** [comment]
> Can you confirm

Yes, I can confirm! Re-run the same CI build, with the (new) floating dependencies it passes now again! :+1:

**Comment by rwjblue** [comment]
Awesome, thank you for checking!
