### ISSUE TITLE
release-it is now a dependency?

### ISSUE THREAD

**Issue by alexlafroscia** [ember-cli/ember-cli-htmlbars#674]
It seems like `release-it` has been added as an `optionalDependency` as of this commit

https://github.com/ember-cli/ember-cli-htmlbars/commit/a798b5f338a3b9a7bc01874a036ea1afb0e4e665

This means that `release-it` becomes an optional _dependency_, rather than a `devDependency`.

Was this an intended change? It introduces a lot of extra installed packages, and I can't imagine why I'd want it in my dependencies as a _user_ of this package.

I noticed due to how many packages were introduced in this PR to `ember-concurrency`, which installed a version of `ember-cli-htmlbars` that's impacted by this change https://github.com/machty/ember-concurrency/pull/410

**Comment by rwjblue** [comment]
BAH! 😭 sorry, will fix

**Comment by rwjblue** [comment]
I wish there was an optional dev dependencies field 😞

**Comment by alexlafroscia** [comment]
It's too bad there isn't!

**Comment by rwjblue** [comment]
Released in https://github.com/ember-cli/ember-cli-htmlbars/releases/tag/v5.6.3
