### ISSUE TITLE
Addon template complier error

### ISSUE THREAD

**Issue by maxwondercorn** [ember-cli/ember-cli-htmlbars#681]
I'm updating an addon to 3.16 and when testing against 3.12 I am seeing a template compiler error:

```sh
Build Error (broccoli-persistent-filter:TemplateCompiler)

EEXIST: file already exists, symlink '/var/folders/02/wq3ycc7n7x5_c81rqcn40g5w0000gn/T/broccoli-2 ....
```

from the error report 

```sh
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: broccoli-persistent-filter:TemplateCompiler
  - originalErrorMessage: EEXIST: file already exists, symlink '/var/folders/02/wq3ycc7n7x5_c81rqcn40g5w0000gn/T/broccoli-26161pamyGGgzMf1J/out-093-funnel_funnel_ember_c3_addon/ember-c3/components/c3-chart.js' -> '/var/folders/02/wq3ycc7n7x5_c81rqcn40g5w0000gn/T/broccoli-26161pamyGGgzMf1J/out-094-broccoli_persistent_filter_template_compiler/ember-c3/components/c3-chart.js'
  - stack: Error: EEXIST: file already exists, symlink '/var/folders/02/wq3ycc7n7x5_c81rqcn40g5w0000gn/T/broccoli-26161pamyGGgzMf1J/out-093-funnel_funnel_ember_c3_addon/ember-c3/components/c3-chart.js' -> '/var/folders/02/wq3ycc7n7x5_c81rqcn40g5w0000gn/T/broccoli-26161pamyGGgzMf1J/out-094-broccoli_persistent_filter_template_compiler/ember-c3/components/c3-chart.js'
    at Object.symlinkSync (fs.js:1169:3)
```

This error messages are different but the issue looks similar to #337.  Prior to the bump to 3.16 the addon did not have a template file.

For a reproduction you can look at the `v4` branch of [ember-c3](https://github.com/Glavin001/ember-c3l).  The ember-try config still has older versions to clean up so `ember try:one ember-lts-3.12  --- ember test` will show the error

**Comment by rwjblue** [comment]
You can only leverage template colocation when running with Ember 3.13+:

https://github.com/ember-cli/ember-cli-htmlbars/blob/e3818be9c648482658fff020409d609fb0ec014e/lib/ember-addon-main.js#L46-L48

**Comment by rwjblue** [comment]
The error definitely sucks though, I'm just not sure how to make it better.

**Comment by maxwondercorn** [comment]
Thanks @rwjblue.  Just need to adjust minimus supported version to 3.13.  Yes the error message could be improved
