### ISSUE TITLE
Emit used components in a template

### ISSUE THREAD

**Issue by khornberg** [ember-cli/ember-cli-htmlbars#69]
Is there a way to emit or list the used components in a template?

Basically, in my application that has an addon with 1000 components, I only want to include the components that I actually use in the application.

My thought is that if I can get a list of components used, then I can filter the tree in addon hooks.

I see in the compiled form of a template:
```
statements: [["content", "outlet", ["loc", [null, [11, 0], [11, 10]]]], ["content", "component-one-from-addon", ["loc", [null, [14, 0], [14, 19]]]], ["content", "component-two-from-addon", ["loc", [null, [17, 0], [17, 17]]]]],
```

Is there any registry of used components? 
When and where would that be available at build time?

This may be related to #47 
Also related: http://discuss.emberjs.com/t/how-to-include-only-a-subset-of-the-files-from-an-addon/9099

**Comment by stefanpenner** [comment]
The template compiler itself would need to provide this (something i have wanted for ages). Unfortunately some templates may include `{{component dynamicName}}` or `{{context.component}}` the later may delegate the component to specify such dependencies. the former ... well im sure something creative could be used.

I would recommend this instead by opened as an RFC to the ember repo, as the ember repo currently provides the actual template compiler. This project merely integrates it with broccoli + ember-cli.
