### ISSUE TITLE
Hashtree is not defined

### ISSUE THREAD

**Issue by pankaj20dec** [ember-cli/ember-cli-htmlbars#73]
Reference error: Hashtree is not defined 
at C:\Windows\System32\node_modules\ember-cli-htmlbars\node_modules\broccoli-filter\node_modules\broccoli-kitchen-sink-helpers

**Comment by Turbo87** [comment]
when and where did this happen?

**Comment by rwjblue** [comment]
I do not think this error is related to ember-cli-htmlbars, closing for now.  Happy to reopen with a reproduction...
