### ISSUE TITLE
dead code? utils.template()

### ISSUE THREAD

**Issue by mehulkar** [ember-cli/ember-cli-htmlbars#746]
I was trying to trace where in v4, the `Ember` global is used and it seems that the culprit is this code path:

https://github.com/ember-cli/ember-cli-htmlbars/blob/212cc389cb81c76f14b8e8e4420607332c7f3c8d/lib/utils.js#L189-L193

In v5 and main, this code path is still _called_

https://github.com/ember-cli/ember-cli-htmlbars/blob/78a29d83b5d2674a929b0e22224f381a8db4149f/lib/ember-addon-main.js#L108-L118

but there is no `template()` export from lib/utils:

https://github.com/ember-cli/ember-cli-htmlbars/blob/v5.7.2/lib/utils.js#L362-L373
https://github.com/ember-cli/ember-cli-htmlbars/blob/78a29d83b5d2674a929b0e22224f381a8db4149f/lib/utils.js#L371-L382

Is this `precompile()` method dead code in recent versions?

**Comment by ef4** [comment]
I think this whole code path is gone from current releases.
