### ISSUE TITLE
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`

### ISSUE THREAD

**Issue by oniofchaos** [ember-cli/ember-cli-htmlbars#77]
```javascript
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`
    at Function.Addon.lookup (/Users/dillonwelch/Code/Work/currica/nsqip-web-ember/node_modules/ember-cli/lib/models/addon.js:896:27)
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`
    at Function.Addon.lookup (/Users/dillonwelch/Code/Work/currica/nsqip-web-ember/node_modules/ember-cli/lib/models/addon.js:896:27)
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`
    at Function.Addon.lookup (/Users/dillonwelch/Code/Work/currica/nsqip-web-ember/node_modules/ember-cli/lib/models/addon.js:896:27)
```

This is using Ember 2.4.3 and ember-cli-htmlbars 1.0.8

**Comment by rwjblue** [comment]
We properly call `this._super` in 1.0.8, I believe you likely have some other addon that is locked to an older version of ember-cli-htmlbars. 

What does `npm ls ember-cli-htmlbars` show?

**Comment by oniofchaos** [comment]
```bash
├─┬ ember-chosen@0.0.23
│ └── ember-cli-htmlbars@0.7.9 
├── ember-cli-htmlbars@1.0.8 
├─┬ ember-cli-jquery-ui@0.0.20
│ └── ember-cli-htmlbars@0.7.6 
```
and then another project of mine using 1.0.3

**Comment by rwjblue** [comment]
Thank you! It is as I suspected, you will need to get `ember-chosen` and `ember-cli-jquery-ui` updated to use ember-cli-htmlbars@1.x.  It is possible that they have already fixed the issue and you just need to update versions, or that you may need to submit a pull request to those projects to fix.

I'm going to close this issue now, but I'm happy to reopen if there is something I am missing.

**Comment by oniofchaos** [comment]
Great, thanks for the debugging assistance.

**Comment by michaelserna** [comment]
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`
    at Function.Addon.lookup (/usr/local/lib/node_modules/ember-cli/lib/models/addon.js:1009:27)

Missing npm packages:
Package: ember-cli
  * Specified: 1.13.8
  * Installed: (not installed)

Run `npm install` to install missing dependencies.


And when I run: npm ls ember-cli-htmlbars 
Output: └── ember-cli-htmlbars@0.7.9

@rwjblue I've npm installed; however, it's saying that ember-cli isn't installed.

**Comment by michaelserna** [comment]
Found your solution here: https://github.com/lytics/ember-cli-release/issues/46

Thanks!

**Comment by lifeinafolder** [comment]
I am still seeing this issue. Versions:

```
node 6.9.1
npm 4.0.5
ember-cli: 2.5.0
ember: 2.5.0
```

```
npm ls ember-cli-htmlbars
└── ember-cli-htmlbars@1.1.1 
```

Any ideas?

**Comment by joelpresence** [comment]
Thanks for responding @kellyselden .

But I don't see how it's fixed?  :-(

This happened when I added the very latest version of ember-cli-spinner ... So I'm not sure how to fix this?  I can't update ember-cli-spinner because it's already the latest version.  Do I file an issue with the maintainer of ember-cli-spinner?

Thanks again!

**Comment by joelpresence** [comment]
```
npm ls ember-cli-htmlbars
media-data-frontend@0.0.0 /Users/joel/src/media_data_frontend
├── ember-cli-htmlbars@1.1.0
└─┬ ember-cli-spinner@0.0.8
  └── ember-cli-htmlbars@0.7.9
```

So I guess it's ember-cli-spinner that needs to update its version of ember-cli-htmlbars?

Thanks.

**Comment by kellyselden** [comment]
> Do I file an issue with the maintainer of ember-cli-spinner?

Yes. It must be updated in all addons using it.

**Comment by joelpresence** [comment]
Thanks @kellyselden .  See attached ember-cli-spinner issue.  I'll update when I hear more from them.
