### ISSUE TITLE
this._super is deprecated for ember-cli v2.6.2

### ISSUE THREAD

**Issue by thesubr00t** [ember-cli/ember-cli-htmlbars#78]
After upgrading to ember-cli v2.6.2 I get:

`DEPRECATION: Overriding init without calling this._super is deprecated. Please call 'this._super.init && this._super.init.apply(this, arguments);' addon: 'ember-cli-htmlbars'`

`    at Function.Addon.lookup (frontend/node_modules/ember-cli/lib/models/addon.js:896:27)`

**Comment by thesubr00t** [comment]
I would submit a pull request but I don't understand why we check for `if (this._super.init)` inside [ember-addon-main.js](https://github.com/ember-cli/ember-cli-htmlbars/blob/b9c4f37c2caa411dc7857ef4e852502fdab59f65/ember-addon-main.js#L12)

**Comment by stefanpenner** [comment]
are you on the latest ember-cli-htmlbars? I suspect you are not, as this repo is fixed.

**Comment by flemse** [comment]
Im experiencing the same and i use:
ember-cli  2.6.2
ember-cli-htmlbars 1.0.8

Afaik that is latest versions

**Comment by thesubr00t** [comment]
@stefanpenner I downgraded my ember-cli version to continue working on my project.

I will try again later and provide feedback. But as @flemse is using the latest release, it may not work as well.

Going to try anyway.

**Comment by rwjblue** [comment]
Please see the resolution/explanation in https://github.com/ember-cli/ember-cli-htmlbars/issues/77.  Basically, using the latest 1.x of ember-cli-htmlbars at the project level does not guarantee that all addons are using that version also.  Those addons will need to update to allow 1.x also.
