### ISSUE TITLE
Overriding init without calling this._super is deprecated

### ISSUE THREAD

**Issue by basz** [ember-cli/ember-cli-htmlbars#79]
seeing deprecation warning

```
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`
    at Function.Addon.lookup (..../node_modules/ember-cli/lib/models/addon.js:896:27)
```

"ember-cli": "^2.4.0",

**Comment by Turbo87** [comment]
@basz what version of `ember-cli-htmlbars` are you using?

as you can see in https://github.com/ember-cli/ember-cli-htmlbars/commit/b3e8b1c82ac279cab2b31122ab43b7cc45019b12 this should've been fixed since at least v1.0.7

**Comment by rwjblue** [comment]
Almost certainly the same as what I said in https://github.com/ember-cli/ember-cli-htmlbars/issues/77.  Closing under that assumption, but I can reopen if `npm ls ember-cli-htmlbars` shows only 1.x versions.

**Comment by basz** [comment]
```
├── ember-cli-htmlbars@1.0.8 
└─┬ ember-notify@5.0.2
  └── ember-cli-htmlbars@0.7.9 
```

Does this mean ember-notify uses an older version?

**Comment by Turbo87** [comment]
@basz correct

**Comment by cesarizu** [comment]
It seems that ember-cli (2.8.0-beta.3) is still generating addons with ember-cli-htmlbars@1.0.3:

https://github.com/ember-cli/ember-addon-output/blob/v2.8.0-beta.3/package.json

**Comment by rwjblue** [comment]
Note the `^` in `"ember-cli-htmlbars": "^1.0.3",`. It specifically allows any version in the 1.x range.

**Comment by cesarizu** [comment]
Yeah that's true. I installed `ember-cli-swiper` and got that error. But it seems that the `^` is missing from that package.
