### ISSUE TITLE
Modifying ast plugin should bust cache

### ISSUE THREAD

**Issue by asakusuma** [ember-cli/ember-cli-htmlbars#84]
Given an addon that has an `htmlbars-ast-plugin`, cached htmlbars files should be busted when the plugin is modifyed. This does not happen. I have to delete the async cache.

``` JavaScript
// Changing this file should bust the cache
var ReWriteStuff = require('re-write-stuff');

module.exports = {
  name: 'my-addon',
  setupPreprocessorRegistry: function() {
    registry.add('htmlbars-ast-plugin', {
      name: 're-write-stuff',
      plugin: ReWriteStuff
    });
  }
};
```

**Comment by rwjblue** [comment]
@asakusuma - Confirm.  I would like to do the same thing that we decide on in https://github.com/babel/broccoli-babel-transpiler/pull/89.

**Comment by stefanpenner** [comment]
i think the API should change to:

```js
 registry.add('htmlbars-ast-plugin', {
      name: 're-write-stuff',
      plugin: { name: 're-write-stuff', relativeTo: __dirname }
    });
```

**Comment by rwjblue** [comment]
Was addressed by https://github.com/ember-cli/ember-cli-htmlbars/pull/90.
