### ISSUE TITLE
ember-cli-htmlbars is opting out of caching due to an AST plugin that does not provide a caching strategy: `v-get`

### ISSUE THREAD

**Issue by rinoldsimon** [ember-cli/ember-cli-htmlbars#91]
Deprecation message while starting Ember serve

> ember-cli-htmlbars is opting out of caching due to an AST plugin that does not provide a caching strategy: `v-get`

**Comment by stefanpenner** [comment]
@rinoldsimon v-get is not from this repo, it is from https://github.com/offirgolan/ember-cp-validations cc @offirgolan

**Comment by offirgolan** [comment]
This issue is in reference to offirgolan/ember-cp-validations#318 which has already been resolved.

**Comment by stefanpenner** [comment]
@offirgolan 👍
